// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MyControlAspNetCore.Models;
using System;

namespace MyControlAspNetCore.Migrations
{
    [DbContext(typeof(MyControlAspNetCoreContext))]
    partial class MyControlAspNetCoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyControlAspNetCore.Models.Registro", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataAlteracao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<bool>("Debito");

                    b.Property<string>("Descricao");

                    b.Property<string>("UsuarioAlterador");

                    b.Property<string>("UsuarioCriador");

                    b.Property<decimal>("Valor");

                    b.HasKey("Guid");

                    b.ToTable("Registro");
                });

            modelBuilder.Entity("MyControlAspNetCore.Models.TipoRegistro", b =>
                {
                    b.Property<Guid>("Guid");

                    b.Property<string>("Cor");

                    b.Property<DateTime>("DataAlteracao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Descricao");

                    b.Property<string>("UsuarioAlterador");

                    b.Property<string>("UsuarioCriador");

                    b.HasKey("Guid");

                    b.ToTable("TipoRegistro");
                });

            modelBuilder.Entity("MyControlAspNetCore.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<bool>("Admin");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Nome");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("Senha");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("MyControlAspNetCore.Models.TipoRegistro", b =>
                {
                    b.HasOne("MyControlAspNetCore.Models.Registro")
                        .WithOne("Tipo")
                        .HasForeignKey("MyControlAspNetCore.Models.TipoRegistro", "Guid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
